### ISSUE TITLE
Insecure password generation.

### ISSUE THREAD

**Issue by mketab** [vapen-hem/Password-database-With-special-stuff#1]
the `random` module should never^1 be used for cryptographic purposes because it uses pseudorandom numbers. The python documentation also advises against it:

"Warning The pseudo-random generators of this module should not be used for security purposes. For security or cryptographic uses, see the `secrets` module."

^1 unless using random.SystemRandom

**Comment by vapen-hem** [comment]
Thanks for the info, ill change it a soon as possible!

**Comment by vapen-hem** [comment]
I have now switched out the random module for the secrets module!
