### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [vapen-hem/Password-database-With-special-stuff#2]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by vapen-hem** [comment]
I didn't really understand that part of the process, so I left it untouched. Now after i bit of research, I think ill go with the AGPL-3.0 LICENSE, I just have to figure out how to do it properly

**Comment by vapen-hem** [comment]
I have now added an AGPL-3.0 LICENSE
