### ISSUE TITLE
Publishing Releases

### ISSUE THREAD

**Issue by mketab** [vapen-hem/Password-database-With-special-stuff#4]
I left an issue a month or so ago and I decided to check back on this project. I noticed that you have directories with version numbers in the repo. The whole point of source control is that you can go back to prior versions without needed to make copies of your code.

GitHub has a really easy solution for this too, just create a release of whatever specific versions you want saved.

**Comment by vapen-hem** [comment]
I have now added releases, instead of having multiple version files in the repository, thanks for the suggestion! and sorry for slow response, i haven't been active here for a while.
